name: SystemC Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Clone and Build SystemC
        run: |
          git clone https://github.com/accellera-official/systemc.git
          cd systemc
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/systemc-install
          make -j$(nproc)
          make install

      - name: Build Your SystemC Program
        run: |
          g++ -I$GITHUB_WORKSPACE/systemc-install/include -L$GITHUB_WORKSPACE/systemc-install/lib -lsystemc conv_withtimings.cpp -o vconv.exe

      - name: Run Simulation
        run: |
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/systemc-install/lib
          ./vconv.exe
